---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include = FALSE}
#Load necessary libraries
library(dplyr)
library(tidyr)
library(knitr)
library(kableExtra)
library(flextable)
library(officer)
library(ggplot2)
library(patchwork)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.height=11, fig.width=7)
fpp <- fp_par(text.align = "left", padding = 3)
Johnson = c("#f6c200","#a00e00","#0086a8","#d04e00","#132b69")
graph_theme_wlegend <- theme(
    strip.background = element_rect(fill = "grey80"),
    strip.text = element_text(face = "bold", size = 12),
    legend.position = c(0.85, 0.8),
    legend.title = element_blank(),
    legend.text = element_text(size = 10),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10, color = 'black'))

graph_theme_nolegend <- theme(
    strip.background = element_rect(fill = "grey80"),
    strip.text = element_text(face = "bold", size = 12),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10, color = 'black'))
```

```{r set table plotting parameters, include = FALSE}
#set table plotting parameters
set_flextable_defaults(
  font.color = "black",
  border.color = "black",
  font.family = 'Times New Roman',
  line_spacing = 1
  )
```

```{r summary stats function, include = FALSE}
summary_stats <- function(df, col, group_vars = NULL) {
  
  if (is.null(group_vars)) {
    # calculate statistics for the entire column
    stats <- c(mean(df[[col]], na.rm = TRUE), 
               sd(df[[col]], na.rm = TRUE), 
               sum(!is.na(df[[col]])), 
               sd(df[[col]], na.rm = TRUE) / sqrt(sum(!is.na(df[[col]]))), 
               min(df[[col]], na.rm = TRUE), 
               max(df[[col]], na.rm = TRUE))
    colnames(stats) <- c("Mean", "SD", "Sample Size", "SE", "Min", "Max")
    return(stats)
  }
  
  # group by one or more variables
  group_df <- df %>% group_by(across(all_of(group_vars)))
  
  stats <- group_df %>% 
    summarize(Mean = mean(!!sym(col), na.rm = TRUE), 
              SD = sd(!!sym(col), na.rm = TRUE), 
              Sample_Size = sum(!is.na(!!sym(col))), 
              SE = SD / sqrt(Sample_Size),
              Min = min(!!sym(col), na.rm = TRUE),
              Max = max(!!sym(col), na.rm = TRUE))
  
  return(stats)
}
```


```{r load datasets, include = FALSE}
#data paths
data_path = "./data/fish_size/"
save_figure_path = "./data/fish_size/figures/" 
save_table_path = "./data/fish_size/tables/"

#load datasets
fish_size = read.csv(paste0(data_path, "biometric_data.csv"))
```

```{r sum stats fish size, include = FALSE}
(fish_size_stats <- fish_size %>% 
  dplyr::group_by(Lake, Species, Treatment) %>% 
  dplyr::summarise(mean_weight = mean(Weight),
                   sd_weight = sd(Weight),
                   mean_length = mean(Total_length),
                   sd_length = sd(Total_length),
                   sample_size = n()))
```

```{r edit size table, include = FALSE}
(size_stats <- 
  fish_size_stats %>% 
  mutate_if(is.numeric, round, 2) %>% 
  mutate(Weight = paste0(mean_weight, " ± ", sd_weight),
         Length = paste0(mean_length,  " ± ", sd_length),
         "Sample size" = sample_size) %>% 
  select(-mean_weight, -sd_weight, -mean_length, -sd_length, -sample_size))

#Rename lakes
size_stats$Lake <- recode(size_stats$Lake, "Muddyfoot" = "A", "BT" = "B", "Cow Paradise" = "C")

# Reorder the Species column within each Lake
size_stats <- size_stats %>%
  mutate(Species = factor(Species, levels = c("Roach", "Perch", "Northern Pike"))) %>%
  arrange(Lake, Species)

# Change "Mix" to "Exposed" in the Treatment column
size_stats <- size_stats %>%
  mutate(Treatment = recode(Treatment, "Mix" = "Exposed"))

# Create the desired format
size_formatted <- size_stats %>%
  group_by(Lake) %>%
  mutate(Lake = ifelse(row_number() == 1, as.character(Lake), "")) %>%
  ungroup()

print(size_formatted)
```

```{r roach table for MS, ft.align = 'left'}
(fish_size_table <- 
  qflextable(size_formatted) %>% 
  fontsize(part = "all", size = 11) %>% 
  bold(part = 'header') %>% 
  set_caption(
    caption = as_paragraph(
      as_chunk("Fish demographic information for individuals in the lake study",
               props = fp_text(font.size = 12, bold = FALSE))),
    align_with_table = FALSE,
    word_stylename = "Table Caption",
    fp_p = fpp))
```


```{r save size table, include = FALSE}
save_as_docx(fish_size_table, 
             path = paste0(save_table_path, "fish_size_summary.docx"))
```
